# Generated by Django 4.1.3 on 2023-01-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
